POST http://localhost:3000/auth/local/signin
Content-Type: application/json

{
    "name": "Joel",
    "password": "24062002",
    "email": "joel.20fit18@gct.ac.in"
}

###
 
POST http://localhost:5000/auth/local/login
Content-Type: application/json

{
    "email": "joel.sr1024@gmail.com",
    "password": "24062002" 
}

###

POST http://localhost:3000/posts/create
Content-Type: application/json

{
    "questions" : ["hello", "world"]
}

###
GET http://localhost:3000/posts/getPosts